config/routes.rb
Rails.application.routes.draw do
  
  get 'top/index'

resources :contacts, only: [:index, :new, :create, :edit, :update ,:destroy] do
  collection do
    post :confirm
  end
end

  root 'top#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :content, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
before_action :set_contact, only: [:edit, :update, :destroy]

  def index
        @contacts = Contact.all
  end

  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end
  
  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
      # 一覧画面へ遷移して"Tweetを作成しました！"とメッセージを表示します。
      redirect_to contacts_path, notice: "Tweetを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end
  
  def edit
  end
  
  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: "Tweetを削除しました！"
  end
  
  def update
    # edit, update, destroyで共通コード

    if @contact.update(contacts_params)
      redirect_to contacts_path, notice: "Tweetを更新しました！"
    else
      render 'edit'
    end
  end

  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
      redirect_to top_index_path, notice: "Tweetありがとうございました！"
    else
      render 'new'
    end
  end
  
  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?  
  end
  
  private
    def contacts_params
      params.require(:contact).permit(:content, :confirm)
    end
    
    # idをキーとして値を取得するメソッド
    def set_contact
      @contact = Contact.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_contacts_path
    elsif action_name == 'edit'
      contact_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, url: choose_new_or_edit) do |f| %>
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= @contact.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :content %>
  <p>本文:<%= @contact.content %></p>
  <%= f.submit "登録する",class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  
  <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
<% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>Tweetを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>Tweetフォーム</h1>
      <%= link_to "つぶやく", new_contact_path, class: 'btn btn-default' %>
    <% @contacts.each do |contact| %>
    <div class="row">
      <p><%= contact.content %></p>
      <%= link_to "編集", edit_contact_path(contact.id), class: 'btn btn-sm btn-success' %>
      <%= link_to "削除", contact_path(contact.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-sm btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<p id="notice"><%= notice %></p>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :content %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "Tweet一覧画面にもどる", contacts_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QaAchieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<header>
</header>
<section class="main-header">
<img src="images-master/achieve.png">
</section>

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p><%= notice %></p>

<h1>Twitter</h1>

<div>
<%= link_to "つぶやく", new_contact_path %>
</div>
<div>
<%= link_to "Tweet一覧画面へ", contacts_path %>
</div>
</div>
<footer>
<p>Twitter</p>
<p>運営会社Rubys</p>
</footer>